data:
  name: nq
  data_path: data/nq/retrieved/validation_with_id.jsonl
  
  max_seq_length: 256
  max_ans_length: 32

  batch_size: 2
  num_workers: 0
  topk_per_query: 50
  test_size: 0.05
  seed: 42

  use_precompute_table: False
  precompute_table_path: None

model:
  model_name: meta-llama/Meta-Llama-3-8B-Instruct
  gen_kwargs:
    do_sample: False
    temperature: 1.0
    top_p: 1
    top_k: null
    max_new_tokens: 32

seed: 42
debug_mode: False  # Only activate when debugging

generate_prompt_name: base

output_dir: /workspaces/kvzip_nlplab/checkpoint
output_file: nq_val_precompute_table_expanded.h5
project_name: caformer
exp_type: multi
