data:
  name: hotpotqa-w
  # data_path: data/hotpotqa-w/retrieved/validation_p_top100_5000.jsonl
  data_path: data/hotpotqa-w/retrieved/validation_10_test.jsonl # Only for test
  
  max_query_length: 32
  max_seq_length: 256
  max_length: 3072
  use_single_context: False

  topk_per_query: 10  # Final number of documents after re-ranking
  batch_size: 1
  seed: 42

model:
  model_name: meta-llama/Meta-Llama-3-8B-Instruct
  gen_kwargs:
    do_sample: False
    temperature: 1.0
    top_p: 1
    top_k: null
    max_new_tokens: 32

caformer:
  model_name_or_path: roberta-base
  query_length: 32      # BLIP-2 default setting
  llm_width:    # Post initialized

  pooling_strategy: max
  dropout: 0.1

  use_linear_proj: True   # To embed as soft-prompt
  ckpt_dir: /workspaces/kvzip_nlplab/checkpoint/stage3_clf_only_train/multi_LR=2e-05_fromST2_BS=16_Epochs=2_Pool=max_T1=0.5_Alpha=1.0_time=20260510-074401
  # ckpt_path: /workspaces/kvzip_nlplab/checkpoint/stage3_clf_only_train/prev_exp/multi_LR=2e-05_fromST2_BS=2_ST=tanh_CMode=split_first_AMode=full_Pool=max_T=2.0_Alpha=1.0/multi-00-001531-valid_loss=0.2582.ckpt

  use_it: True
  
  ### Stage-3
  classifier_mode: split_first   # [random, split_first, kmeans]
  classifier_query_length: 32
  attention_mode: full     # [full, block]
  use_causal: True

seed: 42

generate_prompt_name: base
do_hybrid: True

### Reranking ensemble
ce_reranker_path: BAAI/bge-reranker-base
fusion_method: rrf
fusion_weight: 0.5
rrf_k: 60   # General RRF K value

output_dir: /workspaces/kvzip_nlplab/DISCA/results/disca
project_name: caformer
exp_type: multi
experiment_name: Alpha=0.5