data:
  name: nq
  data_path: data/combined_train_data/sampled_train_data.jsonl
  max_seq_length: 1024
  use_single_context: True

model:
  model_name: meta-llama/Llama-3.1-8B-Instruct
  gen_kwargs:
    do_sample: False
    temperature: 1.0
    top_p: 1
    top_k: null
    max_new_tokens: 32

generate_prompt_name: pure-llm-brief-2
output_dir: src/results/verify_pure
task: base
mode: verify
experiment_name: