data:
  filepath: /workspaces/kvzip_nlplab/KFC/data/combined_train_data/train_features_pn.pt
  batch_size: 128
  num_workers: 4

train:
  learning_rate: 3e-5
  warmup_ratio: 0.1
  max_epochs: 50
  n_class: 2

model:
  n_class: 2
  n_heads: 8
  n_features: 2
  inter_channels: 128
  out_channels: 32
  n_layer: 32
  kernel_size: 5
  dropout: 0.5

seed: 42

project_name: conflict_detector
exp_type: features
trained_dir: /workspaces/kvzip_nlplab/KFC-dev/src/trained_model
output_dir: /workspaces/kvzip_nlplab/KFC-dev/src/train_analysis