data:
  ### half dataset (final)
  # name: mhqa
  # data_path: data/train/mhqa_train_half_force.jsonl

  ### 1/16 dataset (pilot for hypothesis testing)
  name: mhqa
  data_path: data/train/mhqa_train_pilot.jsonl

  max_seq_length: 256
  max_ans_length: 32  # Short answer

  batch_size: 1
  num_workers: 2
  first_topk: 50
  topk_per_query: 10
  test_size: 0.05
  seed: 42

  use_precompute_table: True  # Use pre-compute table or not
  # precompute_table_path: /workspaces/kvzip_nlplab/checkpoint/genloss_precompute_table/llama/short_loss_half_precompute_table.h5     # (No Sys)
  precompute_table_path: /workspaces/kvzip_nlplab/checkpoint/genloss_precompute_table/llama/sys_short_loss_half_precompute_table.h5   # (Sys)

  use_pseudo_answer: False

model:
  model_name: meta-llama/Meta-Llama-3-8B-Instruct
  gen_kwargs:
    do_sample: False
    temperature: 1.0
    top_p: 1
    top_k: null
    max_new_tokens: 32
  padding_side: left    # use left padding for self train

train:
  learning_rate: 2e-5
  warmup_ratio: 0.05
  max_epochs: 2

  topk_per_query: 10  # Top-R reranking docs

  # scaling_factor: 10
  accumulate_grad_batches: 16  # [8, 16, 32]
  append_question: True

  # oracle_mode: marginal   # [whole, marginal, top-1, ..., top-10]
  T: 1.0

  alpha: 0.8        # rankwise guide loss weight, 0 = don't use

  ### Query length
  query_length: 32
  pooling_strategy: mean


seed: 42
debug_mode: False  # Only activate when debugging
use_it: False

generate_prompt_name: base

output_dir: /workspaces/kvzip_nlplab/checkpoint
project_name: caformer
exp_type: self-train
